FizzBuzzApp/FizzBuzzApp/Models/FizzBuzzModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FizzBuzzApp.Models
{
    public class FizzBuzzModel
    {
        [Required(ErrorMessage = "* Input Required")]
        [Display(Name = "Please Enter Number")]
        [Range(1, 1000, ErrorMessage = "* The input value must be between 1 and 1000")]
        public int? Number { get; set; }

        public IPagedList<string> FizzBuzzList { get; set; }

        public int? Page { get; set; }
    }
}

FizzBuzzApp/FizzBuzzApp/Controllers/FizzBuzzController.cs
using FizzBuzzApp.Models;
using FizzBuzzServices.Interfaces;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FizzBuzzApp.Controllers
{
    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzService _fizzBuzzService;
        private const int PageSize = 20;

        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            _fizzBuzzService = fizzBuzzService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            ModelState.Clear();
            var emptyModel = new FizzBuzzModel() { FizzBuzzList = new PagedList<string>(new List<string>(), 1, PageSize) };
            return View("Index", emptyModel);
        }

        [HttpGet]
        public ActionResult GetList(FizzBuzzModel fizzBuzzModel)
        {
            if (ModelState.IsValid)
            {
                var fizzbuzzList = _fizzBuzzService.GetFizzBuzzList(fizzBuzzModel.Number??0);
                if ((fizzBuzzModel.Page ?? 1) * PageSize > fizzbuzzList.Count())
                {
                    fizzBuzzModel.Page = GetMaxPageNumber(fizzbuzzList.Count());
                }
                fizzBuzzModel.FizzBuzzList = fizzbuzzList.ToPagedList(fizzBuzzModel.Page ?? 1, PageSize);
            }
            return View("Index", fizzBuzzModel);
        }

        /// <summary>
        /// Method to get max page number of paged list
        /// </summary>
        /// <param name="totalItems">total items in list</param>
        /// <returns>max page number</returns>
        private int GetMaxPageNumber(double totalItems)
        {
            var mxPageSize = totalItems / PageSize;
            return (int)Math.Ceiling(mxPageSize);
        }
    }
}

FizzBuzzApp/FizzBuzzApp/Views/FizzBuzz/Index.cshtml
@{
    ViewBag.Title = "Fizz Buzz Application";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model FizzBuzzApp.Models.FizzBuzzModel
@using PagedList.Mvc;

<div>
    <div>
        <h2>Fizz Buzz Application</h2>
        @using (@Html.BeginForm("GetList", "FizzBuzz", FormMethod.Get))
        {
            <div>
                @Html.ValidationSummary(true)
                <div>
                    <div>
                        @Html.LabelFor(m => m.Number)
                        @Html.TextBoxFor(m => m.Number)
                    </div>
                    <div>
                        @Html.ValidationMessageFor(m => m.Number)
                    </div>
                </div>
                <input type="submit" value="Get List" />
            </div>
        }
    </div>
    <div>
        @if (Model != null && Model.FizzBuzzList != null && Model.FizzBuzzList.Any())
        { 
            <ul>
                @foreach (var item in Model.FizzBuzzList)
                {
                    var words = item.Split(' ');
                    <li>
                        <div>
                            @foreach (var word in words)
                            {
                                <p class="@word">@word</p>
                            }
                        </div>
                    </li>
                }
            </ul>
            <p>
                @Html.PagedListPager((Model.FizzBuzzList), page => Url.Action("GetList", new { Page = page, Number = Model.Number }), PagedList.Mvc.PagedListRenderOptions.ClassicPlusFirstAndLast)
            </p>
        }
    </div>
</div>

FizzBuzzApp/FizzBuzzApp/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    @RenderBody()
     

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>